baseURL = "https://fergaljoconnor.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Fergal's Homepage"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Fergal O'Connor"
author = "Fergal O'Connor"

description = """Data Engineer. Rust Enthusiast.
Perpetual Tinkerer."""

profilePicture = "images/profile.jpg"

# Size Ratio of Content To Sidebar
contentratio = 0.7

# Read More Links On
readMore = true

displayMode = "light"
disableThemeSwitcher = true

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/fergaljoconnor"

[[params.socialIcons]]
icon = "fas fa-envelope-square"
title = "E-Mail"
url = "mailto:fergaljamesoconnor@gmail.com"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
